# Generated by Django 5.0.6 on 2024-08-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_comentariocontacto_alter_comentario_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='carrera',
            field=models.TextField(verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='nombre',
            field=models.TextField(verbose_name='Nombre'),
        ),
    ]
