# Generated by Django 5.0.6 on 2024-08-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_alter_alumnos_carrera_alter_alumnos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='carrera',
            field=models.TextField(default='carrera'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='turno',
            field=models.TextField(default='artesania', max_length=10),
        ),
    ]
