# Generated by Django 5.0.6 on 2024-08-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='categoria',
            field=models.TextField(default='artesania'),
        ),
    ]
