# Generated by Django 5.0.6 on 2024-08-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_articulos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='ubicacion',
            field=models.TextField(default='ubicacion'),
        ),
    ]
